src/client/module/patches.cpp
fixed announcer only showing 1 when there was 2 drill sargent and snoopdog
temp fixed bg_compassshowenemies for when client gets multilayered implemented
added quit_hard command
=> [patch] little update

src/client/module/patches.cpp
- Dvars use correct flags
- Removed dvar r_vsync patch since it may also cause issues. #22
=> Changed patched dvars

src/client/module/patches.cpp
I decreased the minimum value of the cg_fov from 65.0 to 1.0, increased the maximum value of cg_fovscale from 2.0 to 5.0, and decreased the minimum value of cg_fovscale from 0.5 to 0.1. These changes helps players pick the right combination of cg_fov and cg_fovscale to make their ADS and hip-fire sensitivities and FOVs equal. For example, I prefer to use a cg_fov of 55 and a cg_fovscale of 1.9, allowing me to use the same FOV as MW 2019 at 120 FOV and a 1:1 ADS and hip-fire sensitivity.
=> cg_fovscale and cg_fov changes

src/client/module/patches.cpp
- More "visibility hacks" patches
> `fx_enable/fx_draw` forced to 1 
`r_colorMap/r_lightMap` forced to Unchanged
- Re-ranging the "cg_gun_" dvars
> `cg_gun_x` can greatly improve visiblity when using scoped weapons with a high FOV setting
> ([see image](https://cdn.discordapp.com/attachments/265852764238774273/766231518140956682/3772274b8fad79bf0dd3589d389f265e.png))
=> "cg_gun_" and dvar patches

src/client/module/patches.cpp
I did not realize the utils::hook::jump used more than 5 bytes when a far jump so I fucked the original instructions.
=> #76 fix exec command patch

src/client/game/game.cpp, src/client/game/game.hpp, src/client/game/structs.hpp, src/client/module/command.cpp, src/client/module/dvar_cheats.cpp, src/client/module/gameplay.cpp, src/client/module/patches.cpp
Added in sv_cheats and dvar cheat/replicated protections. Basically sv_cheats is now a replicated dvar so whenever someone joins a game, their sv_cheats is updated to match the server. If sv_cheats is changed to false, all cheat-protected dvars are reset. Only the server (or host of private match) has the ability to change dvars with the replicated flag set externally (i.e with console/cfg/etc). This prevents someone from joining a game and then changing sv_cheats or any other important replicated dvars the server sets. 
Right now sv_cheats is required to be 1 on dedis or private match to change cheat-protected dvars. I think it might make sense to always allow the server host to change any dvar even without allow sv_cheats as a whole but that can be up for discussion. This way if a …
=> Implement sv_cheats

src/client/module/patches.cpp
On resolutions higher than 1080 the game decides to use "fonts/extraBigFont" instead of "fonts/bigFont" to draw the chat fields. This makes the text very stretched and long messages cover half of your screen. See pics below
Before
After
=> Fix chat font on resolutions higher than 1080p

src/client/game/game.cpp, src/client/game/game.hpp, src/client/module/network.cpp, src/client/steam/interfaces/user.cpp
The old steam id generation was not random enough and caused collisions to happen across players. When two players with the same id tried to join a server, there would be a crash rooting in SV_DirectConnect because it thought it needed to reconnect a player that was already in the session state. Temporary fix for now, some method to guarantee no collisions may be needed down the road
=> Change steam_id generation to a more suitable random

src/client/game/game.cpp, src/client/game/game.hpp, src/client/module/bots.cpp, src/client/module/party.cpp
to note: when restarting the map, spawned bots will stay but won't autojoin a team.
added bot_team which will check every 3 sec if bot is spectator then select team if is.
also when fast_restarting at the end of the match when scoreboard is visible the scoreboard will persist and won't go away.
=> add fast_restart command

src/client/component/dvar_cheats.cpp, src/client/game/symbols.hpp
This change allows SetClientDvar to change dvars that are not network dvars. On old cods it would send the SV_GameSendServerCommand with the dvar name as a string. On Ghosts, it converts the dvar name to an ID and sends that instead. The ID is only valid for network dvars (replicated & whatever 0x10 is). This will be handy for scripting when people make their own mods and need the ability to change client dvars
=> allow PlayerCmd_SetClientDvar to change any dvar like old cods

src/client/component/logfile.cpp
The stub was not preserving registers before calling a function as well as comparing a bool result with 'rax' when it should be comparing with 'al'
=> fix chat stub so chat actually works

src/client/component/rcon.cpp
This should restore the old rcon behaviour the server had.
Tools like iw4m had always expected \xFF\xFF\xFF\xFFprint\n as a reply but the new line terminating character was removed.
=> [RCON] Re-Added new line terminating character

src/client/component/console.cpp, src/client/component/rcon.cpp
After #395 print_stub function is no longer needed therefore I decided to remove it.
Also renamed build_status_buffer from std::string to auto to match all other variable declarations in the file.
Finally, I re-wrote an if statement so the code may be shorter in length and perhaps easier to read in my opinion.
Feel free to let me know if the "if statement" was originally written the way you prefer.
=> [RCON] Minor refactoring

src/client/component/party.cpp
Previous PR contained a unused stub. But according to @fedddddd it's still necessary to port over from S1x. This PR adds the hook for this particular stub.
More information see https://github.com/XLabsProject/iw6x-client/pull/503
=> Hook disconnect command

src/client/component/gameplay.cpp, src/client/game/dvars.cpp, src/client/game/dvars.hpp, src/client/game/structs.hpp, src/client/game/symbols.hpp
Adds dvar g_enableElevators.
If set to 1 elevators will be possible again.
Because the elevator glitch was patched this would be the only way to do it (as far as I am aware). I was told by many it makes sense to add this feature because some trickshotting servers might find it useful (as regular cod4 style elevators have been patched). I've seen trickshotting servers on IW5 make the same exact modification to the engine and when they were open they were somewhat popular.
Video: [YT](https://youtu.be/9DkHmDOy0No)
* [xoxor4d](https://github.com/xoxor4d) - I followed his research article about elevators on MW2. He also told me what he modified on other games to depatch elevators.
=> [Feature] Elevators

src/client/component/gameplay.cpp, src/client/game/dvars.cpp, src/client/game/dvars.hpp, src/client/game/symbols.hpp
- bg_bouncingAllAngles, this forces the game to make the player bounce more easily (won't work unless the other dvar is set to true)
- pm_bouncing is renamed to bg_bouncing as the pm_prefix is non-standard. bg = both games, dvars are replicated so it is a more fitting prefix.
- Well tested
This feature comes from IW4x  where it was thoroughly tested by people other than me (https://github.com/XLabsProject/iw4x-client/pull/158). The engine behaves the same way on this game too so it was a straightforward port.
=> Bouncing from all angles

src/client/component/ultrawide.cpp
Why are we allocating a vector? lol
Also replaced dvar_findvar because it is quite silly to look up the dvar each time the function is called (especially when we are registering the dvar the same component).
=> Refactor ultrawide

src/client/component/server_list.cpp, src/client/component/ui_scripting.cpp, src/client/game/symbols.hpp
Never got this crash on iw6x or s1x but I did on h2-mod (MW2CR), happened occasionally when leaving a mission. LUI starts up from the main thread while `r_endframe` (which then calls ui_scripting::run_frame) is being called from the render thread.
I also changed `size_t` to `int` in `server_list` `ui_feeder_item_text` since I noticed the values for the ping column were gone and this was due to the comparison between those two types not working anymore for some reason.
=> Fix potential LUI scripting crash

src/client/component/ui_scripting.cpp, src/client/game/symbols.hpp
Converted functions now get deleted as soon as the associated `cclosure` is deleted, fixes potential memory leaks. 
Removed `reloaduiscripts` since `lui_restart` should be used instead.
=> More LUI scripting fixes

src/client/component/network.cpp, src/client/game/symbols.hpp
fixes #204 / #606. redirects Sys_SendPacket to go straight to raw socket without trying to copy data to limited buffer first
=> Fix sending packets longer than 1288 bytes

src/client/game/scripting/lua/context.hpp, src/client/std_include.hpp
When I updated the project to c++20 dialect I made the mistake to place a #pragma warning(disable: 5056) in the global preached header.
This is not good as the warning is legit.
Sol2 claims only to support c++17 https://github.com/ThePhD/sol2#supported-compilers
So this pull request will disable this c++20 warning only where it's needed and leave it on for the rest of the project
=> Move sol2 specific warning to where it's needed

src/client/component/gsc/script_loading.cpp
This seems to work without crashes, so let's go with it.
Pasted with ❤️ from https://github.com/fedddddd/h2-mod/commit/69f251bfda0f45d6fe30a0d0ba1c0f2729d6c4f7
(the underlying bug fed was trying to fix on h2-mod should not be here on IW6x).
=> refactor(gsc): Use Hunk memory
