XLabsProject/iw6x-client

- src/client/module/steam_proxy.cpp
Updated steam intergation image because I feel the snake is better then the ghost
> updated steam intergration picture

- src/client/module/patches.cpp
I will need to learn latter on how to be able to just get setplayerdata for this stuff but I think it maybe to hard for me right now to do that
> [Patch] Included all squad members for level 60

- src/client/module/patches.cpp
> Fixed bug with pm_bouncing enabled in multiplayer

- src/client/module/gameplay.cpp
- src/client/module/patches.cpp
Moved gameplay related patches from patches module into new gameplay module
Fixes #39
> Added new gameplay module and fixed g_speed bug

- src/client/game/game.cpp
- src/client/game/game.hpp
- src/client/module/scheduler.cpp
- src/client/module/scheduler.hpp
Added main & server threads to the scheduler so that when dedis are done they can use the scheduler. plus not everything should go on the render thread :P
> scheduler addons

- src/client/module/patches.cpp
> Patched r_fog

- src/client/module/colors.cpp
- src/client/module/patches.cpp
> Block changing name in-game & remove colors from overhead names

- .github/workflows/build.yml
- README.md
> Set up GitHub Actions

- src/client/module/patches.cpp
Just calling the Dvar_RegisterFloat function again doesn't change the dvar flags. Need to remove the cheat-protected flag on it so people can use on servers without sv_cheats enabled
> hook calls for cg_gun_ dvars to remove flags

- src/client/module/server_list.cpp
> Updated DPServer IP Address

- src/client/game/game.cpp
- src/client/game/game.hpp
- src/client/module/network.cpp
- src/client/module/network.hpp
- src/client/module/rcon.cpp
Add in rcon as well as the status command and fixing the print oob command
> #91 rcon and status command

- src/client/game/dvars.cpp
- src/client/game/dvars.hpp
- src/client/game/game.cpp
- src/client/game/game.hpp
- src/client/module/patches.cpp
> patch Dvar_Command to print values  if no values are given like CoD4

- src/client/module/colors.cpp
- src/client/module/discord.cpp
- src/client/utils/string.cpp
- src/client/utils/string.hpp
> display the proper hostname in discord presence #94 

- src/client/game/game.cpp
- src/client/game/game.hpp
GetCurrentCoDPlayMode returns:
2 = Multiplayer
3 = Extinction
4 = Squad
> Add some functions

- src/client/module/stats.cpp
> unlock all camos

- src/client/game/dvars.cpp
- src/client/game/dvars.hpp
- src/client/module/fps.cpp
- src/client/module/gameplay.cpp
Simple ping counter that renders the same way as CG_DrawFPS
I'm sure there are better ways to do it but as commented in the code i don't want to mess things up, this is simply a start but if you're aiming for a early pre release this month i'm sure the playerbase would appreciate a ping counter.
> Added a simple ping counter

- .github/workflows/build.yml
- CHANGELOG.md
- appveyor.yml
> Implement release process automation

- src/client/game/game.cpp
- src/client/game/game.hpp
- src/client/module/bots.cpp
- src/client/module/party.cpp
- src/client/module/patches.cpp
+ /clientkick <clientNum>
+ /kick <playerName>
> Add clientkick and kick commands

- src/client/game/game.cpp
- src/client/game/game.hpp
- src/client/module/binding.cpp
> added binding

- src/client/module/console.cpp
- src/client/module/console.hpp
- src/client/module/dedicated_info.cpp
Aslo make console window bigger on dedicated.
> Show infomation on title of the dedicated console

- src/client/game/game.cpp
- src/client/game/game.hpp
- src/client/game/structs.hpp
- src/client/module/command.cpp
here are some weapons codenames:
defaultweapon_mp
iw6_ak12_mp
iw6_ameli_mp
iw6_arx160_mp
iw6_bren_mp
iw6_cbjms_mp
iw6_fads_mp
iw6_fp6_mp
iw6_g28_mp
iw6_gm6_mp
iw6_gm6helisnipe_mp
iw6_honeybadger_mp
iw6_imbel_mp
iw6_k7_mp
iw6_kac_mp
iw6_knifeonly_mp
iw6_knifeonlyjugg_mp
iw6_kriss_mp
iw6_l115a3_mp
iw6_lsat_mp
iw6_m9a1_mp
iw6_m27_mp
iw6_maaws_mp
iw6_maawschild_mp
iw6_maawshoming_mp
iw6_magnum_mp
iw6_magnumhorde_mp
iw6_magnumjugg_mp
iw6_maul_mp
iw6_microtar_mp
iw6_minigun_mp
iw6_minigunjugg_mp
iw6_mk14_mp
iw6_mk32_mp
iw6_mk32horde_mp
iw6_mp443_mp
iw6_msbs_mp
iw6_mts255_mp
iw6_p226_mp
iw6_p226jugg_mp
iw6_panzerfaust3_mp
iw6_pdw_mp
iw6_pp19_mp
iw6_r5rgp_mp
iw6_rgm_mp
iw6_riotshield_mp
iw6_riotshieldjugg_mp
iw6_sc2010_mp
iw6_svu_mp
iw6_usr_mp
iw6_uts15_mp
iw6_vepr_mp
iw6_vks_mp
> add give command

- src/client/component/gameplay.cpp
- src/client/game/dvars.cpp
- src/client/game/dvars.hpp
* jump_slowDownEnable
* jump_enableFallDamage
* jump_height
* jump_ladderPushVel
> Implement some jump dvars

- src/client/component/scripting.cpp
for some reason with the code caused some extinction maps to not load and fx overflow out should fix #319 so people can play on the extinction maps that was overflowing until it can be fixed
> [fix]  mayday not loading

- src/client/component/scripting.cpp
This will fix both the loading, and the error occurring again once using fast_restart.
> Actual fix for mayday

- src/client/component/command.cpp
- src/client/component/game_console.cpp
- src/client/component/game_console.hpp
- src/client/game/structs.hpp
- src/client/game/symbols.hpp
- add listassetpool, consoleList cmds
- fix console clearing not resetting line offset
- fix trying to open server list lui from in-game
- fix console version string overlapping console output text
- for some reason in iw6 g_zones_0 sometimes leads to garbage data, need to investigate for listassetpool
> bring some changes from s1x to iw6x

- src/client/component/game_console.cpp
- src/client/component/party.cpp
- src/client/component/rcon.cpp
..Use sizeof operator more often to calculate buffer size when using functions such as strncpy_s
> [S1X] Use sizeof operator

- .github/workflows/build.yml
- .github/workflows/draft-new-release.yml
- .github/workflows/release.yml
- src/client/component/game_module.cpp
- src/client/component/redirect.cpp
- src/client/component/splash.cpp
- src/client/component/updater.cpp
- src/client/main.cpp
the environment variable for ghost should be: XLABS_GHOSTS_INSTALL
> x labs launcher support

- src/client/component/auth.cpp
- src/client/std_include.hpp
- src/common/utils/smbios.cpp
- src/common/utils/smbios.hpp
Ported guid generation + guid command from S1x to IW6x.
> Generate guid based on smbios uuid

- src/client/component/dedicated.cpp
- src/client/component/system_check.cpp
- src/client/main.cpp
Ported the minimum required RAM for dedicated servers + a small cleanup of main.cpp from S1x to IW6x.
> Reduced minimum required memory for dedicated servers

- src/client/component/command.cpp
will test when I got time or if someone else can. this was requested for s1x but wanted to add for IW6x and make sure it works
> notarget cmd (sp)

- src/client/component/scripting.cpp
I've reverted a part of a previous commit and this fixes issue #444
Although I'm not entirely sure why.
> Revert changes is_pre_main_stub (Scripting)

- src/client/component/command.cpp
- src/client/game/structs.hpp
- fixed notarget command for singleplayer
- added godmode command for singleplayer
- added notarget command for multiplayer
> Notarget & god command 

- src/common/utils/binary_resource.cpp
write_exitisting_temp_file -> write_existing_temp_file
> Fixed typo in binary_resource.cpp

- src/client/component/party.cpp
Ported the kick/drop reason from S1x to IW6x.
> Show kick reason

- src/client/component/command.cpp
This command was mentioned in the modding channel of the discord server.
Why not add it I thought
> Add vstr command

- src/client/component/bots.cpp
- src/client/component/dedicated_info.cpp
- src/client/component/game_console.cpp
- src/client/component/party.cpp
- src/client/component/party.hpp
- src/client/component/rcon.cpp
- src/client/game/structs.hpp
Shoud be a nice addition to check for these things. I also added the clientstatus enum which was missing.
> Bring 'is server full' s1x check to the bots module

- src/client/component/bullet.cpp
- src/client/game/dvars.cpp
- src/client/game/dvars.hpp
I just ported the code for `bg_surfacePenetration` dvar to change the penetrationDepth.
> Implementing bg_surfacePenetration dvar 

- src/client/component/fastfiles.cpp
- src/client/game/dvars.cpp
- src/client/game/dvars.hpp
- src/client/game/structs.hpp
- src/client/game/symbols.hpp
let's not forget to credit fed
> Add gsc dumper (bin format)

- src/client/component/bots.cpp
- src/client/component/command.cpp
- src/client/component/dedicated.cpp
- src/client/component/dvar_cheats.cpp
- src/client/component/map_rotation.cpp
- src/client/component/party.cpp
- src/client/component/party.hpp
- src/client/game/dvars.cpp
- src/client/game/dvars.hpp
- src/client/game/symbols.hpp
Closes #49 (has been implemented some time ago)
> cleanup of some commands & sv_cheats usage

- src/client/component/scripting.cpp
- src/client/game/scripting/execution.cpp
- src/client/game/scripting/functions.cpp
- src/client/game/scripting/lua/context.cpp
&  cleanup 
Actual bug fix was done in functions.cpp
> Fix bug in lua scripts

- data/maps/mp/gametypes/_menus.gsc
- src/client/component/dvars.cpp
- src/client/component/dvars.hpp
- src/client/component/ranked.cpp
Thanks to @fedddddd 
the `_menus.gsc` placed in localappdata has two patches for "force_ranking"
> Ranked for IW6x

- src/client/component/notifies.cpp
and optimization of the log print function call
> fix(notifes): \x15 -> \x1F

- src/client/component/gameplay.cpp
- src/client/game/dvars.cpp
- src/client/game/dvars.hpp
- src/client/game/symbols.hpp
> fix: re-write stubs

- data/ui_scripts/server_filter/__init__.lua
- data/ui_scripts/server_list/__init__.lua
- src/client/component/server_list.cpp
- src/common/utils/string.cpp
Reverts XLabsProject/iw6x-client#792
Not anymore
> fix(string): return value

- src/client/component/scripting.cpp
> fix(scripting): solve one mem leak
